import type { Property } from '@/types'

export const MOCK_PROPERTIES: Property[] = [
  {
    id: 'prop-001',
    title: 'Stunning 5-Bedroom Villa with Pool — Runda',
    description: 'A magnificent villa nestled in the serene Runda estate. Features an infinity pool, mature gardens, and panoramic views. Fully automated smart home system.',
    type: 'villa',
    listingType: 'sale',
    status: 'active',
    price: 85_000_000,
    currency: 'KES',
    location: { address: 'Runda Close', city: 'Nairobi', country: 'Kenya', zipCode: '00100', lat: -1.2120, lng: 36.8097, neighbourhood: 'Runda' },
    features: { bedrooms: 5, bathrooms: 5, floors: 2, garages: 3, sqMeters: 680, yearBuilt: 2019, furnished: true, petFriendly: true, amenities: ['Swimming Pool', 'Gym', 'Security', 'Garden', 'Smart Home', 'Backup Generator'] },
    media: { images: ['https://images.unsplash.com/photo-1564013799919-ab600027ffc6?w=800'], videos: [], tourUrl: '' },
    ownerId: 'user-001',
    views: 2847,
    favourites: 134,
    createdAt: new Date('2024-11-01'),
    updatedAt: new Date('2024-11-01'),
  },
  {
    id: 'prop-002',
    title: 'Modern 3-Bedroom Apartment — Westlands',
    description: 'Sleek, contemporary apartment on the 14th floor with breathtaking city views. Premium finishes throughout, open-plan kitchen, and a private balcony.',
    type: 'apartment',
    listingType: 'rent',
    status: 'active',
    price: 120_000,
    currency: 'KES',
    location: { address: 'Westlands Road', city: 'Nairobi', country: 'Kenya', zipCode: '00100', lat: -1.2676, lng: 36.8082, neighbourhood: 'Westlands' },
    features: { bedrooms: 3, bathrooms: 2, floors: 1, garages: 1, sqMeters: 185, yearBuilt: 2021, furnished: true, petFriendly: false, amenities: ['Gym', 'Security', 'Balcony', 'Air Conditioning', 'Parking', 'CCTV'] },
    media: { images: ['https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=800'] },
    ownerId: 'user-002',
    views: 1523,
    favourites: 89,
    createdAt: new Date('2024-12-01'),
    updatedAt: new Date('2024-12-01'),
  },
  {
    id: 'prop-003',
    title: 'Executive 4-Bedroom Home with Garden — Karen',
    description: 'Elegant family home on a half-acre plot in the leafy Karen suburb. Spacious entertaining areas, mature garden, and staff quarters. Close to top schools.',
    type: 'house',
    listingType: 'sale',
    status: 'active',
    price: 42_000_000,
    currency: 'KES',
    location: { address: 'Karen Hardy', city: 'Nairobi', country: 'Kenya', zipCode: '00100', lat: -1.3478, lng: 36.7226, neighbourhood: 'Karen' },
    features: { bedrooms: 4, bathrooms: 3, floors: 2, garages: 2, sqMeters: 380, yearBuilt: 2016, furnished: false, petFriendly: true, amenities: ['Security', 'Garden', 'Parking', 'Backup Generator', 'Borehole Water', 'Staff Quarters'] },
    media: { images: ['https://images.unsplash.com/photo-1583608205776-bfd35f0d9f83?w=800'] },
    ownerId: 'user-003',
    views: 987,
    favourites: 62,
    createdAt: new Date('2025-01-10'),
    updatedAt: new Date('2025-01-10'),
  },
  {
    id: 'prop-004',
    title: 'Furnished Studio Room — Kilimani',
    description: 'Cosy fully-furnished studio ideal for a young professional. Walking distance to Junction Mall, restaurants, and public transport. All bills included.',
    type: 'room',
    listingType: 'rent',
    status: 'active',
    price: 28_000,
    currency: 'KES',
    location: { address: 'Kilimani Estate', city: 'Nairobi', country: 'Kenya', zipCode: '00100', lat: -1.2921, lng: 36.7859, neighbourhood: 'Kilimani' },
    features: { bedrooms: 1, bathrooms: 1, floors: 1, garages: 0, sqMeters: 42, yearBuilt: 2018, furnished: true, petFriendly: false, amenities: ['Security', 'Air Conditioning', 'Parking', 'CCTV'] },
    media: { images: ['https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800'] },
    ownerId: 'user-004',
    views: 3201,
    favourites: 201,
    createdAt: new Date('2025-02-01'),
    updatedAt: new Date('2025-02-01'),
  },
  {
    id: 'prop-005',
    title: 'Beachfront Villa — Diani, Mombasa',
    description: 'A rare beachfront property right on Diani Beach. Six bedrooms, three reception areas, private pool, and direct beach access. Ideal as a luxury home or holiday rental.',
    type: 'villa',
    listingType: 'sale',
    status: 'active',
    price: 220_000_000,
    currency: 'KES',
    location: { address: 'Diani Beach Road', city: 'Mombasa', country: 'Kenya', zipCode: '80401', lat: -4.3167, lng: 39.5833, neighbourhood: 'Diani' },
    features: { bedrooms: 6, bathrooms: 6, floors: 2, garages: 4, sqMeters: 950, yearBuilt: 2020, furnished: true, petFriendly: true, amenities: ['Swimming Pool', 'Garden', 'Security', 'Rooftop Terrace', 'Solar Power', 'Backup Generator', 'Smart Home'] },
    media: { images: ['https://images.unsplash.com/photo-1613977257363-707ba9348227?w=800'] },
    ownerId: 'user-005',
    views: 5640,
    favourites: 412,
    createdAt: new Date('2025-01-25'),
    updatedAt: new Date('2025-01-25'),
  },
  {
    id: 'prop-006',
    title: '2-Bedroom Apartment with City View — Lavington',
    description: 'Well-finished apartment in a quiet, secure complex. Open-plan living, modern kitchen, and a generous balcony overlooking the Nairobi skyline.',
    type: 'apartment',
    listingType: 'rent',
    status: 'active',
    price: 75_000,
    currency: 'KES',
    location: { address: 'Lavington Green', city: 'Nairobi', country: 'Kenya', zipCode: '00100', lat: -1.2803, lng: 36.7660, neighbourhood: 'Lavington' },
    features: { bedrooms: 2, bathrooms: 2, floors: 1, garages: 1, sqMeters: 120, yearBuilt: 2022, furnished: false, petFriendly: true, amenities: ['Security', 'Gym', 'Parking', 'Balcony', 'CCTV', 'Backup Generator'] },
    media: { images: ['https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=800'] },
    ownerId: 'user-006',
    views: 1876,
    favourites: 97,
    createdAt: new Date('2025-02-15'),
    updatedAt: new Date('2025-02-15'),
  },
]
